<?php
$title = 'Add new mahasiswa';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<?php
$nim = $form->get('nim');
$nim->setAttribute('class', 'form-control');
$nim->setAttribute('placeholder', 'Mahasiswa Nim');

$nama = $form->get('nama');
$nama->setAttribute('class', 'form-control');
$nama->setAttribute('placeholder', 'Mahasiswa Nama');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('mahasiswa', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
	<?= $this->formLabel($nim); ?>
	<?= $this->formElement($nim); ?>
	<?= $this->formElementErrors()->render($nim, ['class' => 'help-block']); ?>
</div>

<div class="form-group">
	<?= $this->formLabel($nama); ?>
	<?= $this->formElement($nama); ?>
	<?= $this->formElementErrors()->render($nama, ['class' => 'help-block']); ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
