<?php
$title = 'Add new posts';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<form method="POST" name="blog" action="/blog/add" id="blog">
<div class="form-group">
	<label>Title</label>
	<input type="text" name="title" class="form-control">
</div>
<div class="form-group">
	<label>Text</label>
	<input type="text" name="text" class="form-control">
</div>
<input type="submit" name="submit" class="btn btn-primary" value="Add">
</form>
