<?php
$title = 'My albums';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('blog', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Text</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $post) : ?>
    <tr>
        <td><?= $this->escapeHtml($post->title) ?></td>
        <td><?= $this->escapeHtml($post->text) ?></td>
        <td>
            <a href="<?= $this->url('blog', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
            <a href="<?= $this->url('blog', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?= $this->paginationControl(
	$this->paginator,
	'sliding',
	'partial/paginator',
	['route' => 'blog']
); ?>
