<h1>Add new user</h1>
<form action="<?= $this->url('user', ['action' => 'add']); ?>" method="POST">
<div class="form-group">
	<input type="text" id="title" class="form-control" name="title" placeholder="Title" class="help-block" required>
</div>
<div class="form-group">
	<input type="text" id="artist" class="form-control" name="artist" placeholder="Artist" class="help-block" required>
</div>
<input type="submit" class="btn btn-primary" value="Add">
</form>
