<h1>Add new user</h1>
<form action="<?= $this->url('user', ['action' => 'edit', 'id' => $id, ]); ?>" method="POST">
<div class="form-group">
	<input type="text" id="title" class="form-control" name="title" placeholder="Title" class="help-block" value="<?= $this->user->title; ?>" required>
</div>
<div class="form-group">
	<input type="text" id="artist" class="form-control" name="artist" placeholder="Artist" class="help-block" value="<?= $this->user->artist; ?>" required>
</div>
<input type="submit" class="btn btn-primary" value="Edit">
