<?php
$title = 'My user';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('user', ['action' => 'add']) ?>">Add new user</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->list as $user) : ?>
    <tr>
        <td><?= $this->escapeHtml($user->title) ?></td>
        <td><?= $this->escapeHtml($user->artist) ?></td>
        <td>
            <a href="<?= $this->url('user', ['action' => 'edit', 'id' => $user->id]) ?>">Edit</a>
            <a href="<?= $this->url('user', ['action' => 'delete', 'id' => $user->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?= $this->paginationControl(
	$this->list,
	'sliding',
	'partial/paginator',
	['route' => 'user']
); ?>
