<?php
$title = 'My user';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('user', ['action' => 'add']) ?>">Add new user</a>
</p>

<table class="table">
<tr>
    <th>Agency Code</th>
    <th>Username</th>
    <th>Trading Name</th>
    <th>Group</th>
    <th>Last Login</th>
    <th>Last Transaction</th>
    <th>Deposit</th>
    <th>Status</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->list as $user) : ?>
    <tr>
        <td><?= $user->user_code . '-' . sprintf("%06d", $user->user_id); ?></td>
        <td><?= $user->user_name; ?></td>
        <td><?= $user->user_trading_name; ?></td>
        <td><?= $user->group_name; ?></td>
        <td><?= !empty($user->user_login) ? date('d/m/Y H:i:s', $user->user_login) : 'Never Login'; ?></td>
        <td><?= !empty($user->user_last_order) ? date('d/m/Y H:i:s', $user->user_last_order) : 'Never Transaction'; ?></td>
        <td align="right"><?= number_format($user->deposit_value); ?></td>
        <td><?= $user->user_status; ?></td>
        <td>
            <a href="<?= $this->url('user', ['action' => 'edit', 'id' => $user->user_id]) ?>">Edit</a>
            <a href="<?= $this->url('user', ['action' => 'active', 'id' => $user->user_id]) ?>">A</a>
            <a href="<?= $this->url('user', ['action' => 'inactive', 'id' => $user->user_id]) ?>">I</a>
            <a href="<?= $this->url('user', ['action' => 'delete', 'id' => $user->user_id]) ?>">Del</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?= $this->paginationControl(
	$this->list,
	'sliding',
	'partial/paginator',
	['route' => 'user']
); ?>
